[alembic]

# Location of migration scripts
script_location = %(here)s/migrations

# Add project root to Python path
prepend_sys_path = .

# Path separator
path_separator = os

# Database Connection URL
# Note: %%40 represents @ in the password
sqlalchemy.url = postgresql://postgres:Pavan%%40123@localhost:5432/DoctorAppointementBooking


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic


[logger_root]
level = WARNING
handlers = console
qualname =


[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine


[logger_alembic]
level = INFO
handlers =
qualname = alembic


[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic


[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S