"""add appointment reminder sent field

Revision ID: 39339e20d9cf
Revises: 577c882a5590
Create Date: 2026-07-14 14:43:05.218549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39339e20d9cf'
down_revision: Union[str, Sequence[str], None] = '577c882a5590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctors', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('doctors', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('doctors', 'clinic',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('doctors', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('doctors', 'education',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_doctors_city'), table_name='doctors')
    op.alter_column('slots', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slots', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_doctors_city'), 'doctors', ['city'], unique=False)
    op.alter_column('doctors', 'education',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('doctors', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('doctors', 'clinic',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('doctors', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('doctors', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('appointments', 'reminder_sent')
    # ### end Alembic commands ###
