"""create users doctors slots appointments tables

Revision ID: 74b6699fb3ad
Revises: e9c0a8465102
Create Date: 2026-07-09 15:08:57.825924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b6699fb3ad'
down_revision: Union[str, Sequence[str], None] = 'e9c0a8465102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
