"""create database tables

Revision ID: e9c0a8465102
Revises: fdd8d36382a8
Create Date: 2026-07-09 14:37:21.292770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c0a8465102'
down_revision: Union[str, Sequence[str], None] = 'fdd8d36382a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('speciality', sa.String(length=100), nullable=False))
    op.add_column('doctors', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_doctors_specialty'), table_name='doctors')
    op.create_index(op.f('ix_doctors_speciality'), 'doctors', ['speciality'], unique=False)
    op.drop_column('doctors', 'specialty')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.add_column('doctors', sa.Column('specialty', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_doctors_speciality'), table_name='doctors')
    op.create_index(op.f('ix_doctors_specialty'), 'doctors', ['specialty'], unique=False)
    op.drop_column('doctors', 'is_active')
    op.drop_column('doctors', 'speciality')
    # ### end Alembic commands ###
